### ISSUE TITLE
How can i use the user info coming from Json?

### ISSUE THREAD

**Issue by user97972** [vince-nyanga/flutter_bloc_authentication#1]
I am trying to modify services/authentication_service.dart as i am trying to use Json for authentication but my authentication returns user information null. Here is my code

`  Future<User> signIn(String email, String password) async {

    WidgetsFlutterBinding.ensureInitialized();
    final http.Response response = await http.post("$SERVER_IP/rest-auth/login/",
        body: jsonEncode(<String, String>{
          'email':email,
          'password':password,
        }),
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
          HttpHeaders.authorizationHeader: "9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b",
        },
    );
    if (response.statusCode == 200) {

      print(response.body);
      return User.fromJSON(json.decode(response.body));
    }

    else {
    throw AuthenticationException(message: 'Wrong email or password');
    }
  }
`

The data returns something like this

`"user": {
   "id": "id here",
   "email": "userabc@gmail.com",
   "username": "userabc",
}`

The authentication is fine, i can get the data successfully but data is null when i try to decode it in User.
How can i return User() the way that it returns the JSON data?

**Comment by vince-nyanga** [comment]
Hi, 

I think you need to take a look at your `User.fromJSON` factory method. Do you have passing unit tests for that method?

**Comment by user97972** [comment]
I have already done that. Solution is 
`

    if (response.statusCode == 200) {

      var responseJson = json.decode(response.body);
      return User.fromJSON(responseJson['user']);

    }

`
