### ISSUE TITLE
How to use localstorage in authentication ?

### ISSUE THREAD

**Issue by leejunofan** [vince-nyanga/flutter_bloc_authentication#2]
i loggedin and i can see home page but i closed app and i opened app again its showing login page ,, i need to see home page , how to handle it ?

**Comment by vince-nyanga** [comment]
I think you can use something like [shared_preferences](https://pub.dev/packages/shared_preferences) to save a property that indicates that the person has been authenticated already. I'm not 100% sure that will be the best option in this case but you could at least take a look at it.

**Comment by leejunofan** [comment]
yes i have used shared_preferences and i complete it ! .. Thank you for suggestion
