### ISSUE TITLE
nested blocbuilder

### ISSUE THREAD

**Issue by niligithub0** [vince-nyanga/flutter_bloc_authentication#3]
Hi ,Could you explain why you use nested blocbuider in your project ?Is it really necessary? I mean in [main.dart](https://github.com/vince-nyanga/flutter_bloc_authentication/blob/master/lib/main.dart#L31)  and [login_page.dart](https://github.com/vince-nyanga/flutter_bloc_authentication/blob/master/lib/pages/login_page.dart#L15) you use
`BlocBuilder<AuthenticationBloc, AuthenticationState>`. Why don't you check the [state](https://github.com/vince-nyanga/flutter_bloc_authentication/blob/master/lib/blocs/authentication/authentication_state.dart) condition all in blocbuilder in [main.dart ](https://github.com/vince-nyanga/flutter_bloc_authentication/blob/master/lib/main.dart#L31) ?

**Comment by vince-nyanga** [comment]
Hi, you're right. It's not necessary.
